#!/bin/bash
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
DEST_REPO=""
DEST_TAG=""
MATLAB_VERSION="r2021b"
MATLAB_PRODUCTS="MATLAB MATLAB_Parallel_Server Parallel_Computing_Toolbox"
PUSH=false
NOCACHE=false

function usage {
	cat <<EOF
Usage:
	$0 [options]
Options:
	--repo            <docker_repo>   Docker repo for container (required)
	--tag             <docker_tag>    Docker tag for repo (required)
        --matlab-version  <version>       Matlab version (default: $MATLAB_VERSION)
	--matlab-products <products>      Matlab products/toolbox
                                          (default: $MATLAB_PRODUCTS)
        --push                            Push container (default: $PUSH)
        --no-cache                        Docker build w/o cache (default: $NOCACHE)
Examples:
	$0 --repo example.org/matlab/matlab --tag latest
EOF
}

DOCKER=$(type -p docker)
if [ -z "$DOCKER" ]; then
  cat <<EOF
Could not find 'docker' in PATH. It may not be installed.
EOF
  exit 1
fi

while [ $# -gt 0 ]; do
  case $1 in
    --help)
      usage
      exit 0
      ;;
    --repo)
      DEST_REPO=$2
      shift; shift
      ;;
    --tag)
      DEST_TAG=$2
      shift; shift
      ;;
    --matlab-version)
      MATLAB_VERSION=$2
      shift; shift
      ;;
    --matlab-products)
      MATLAB_PRODUCTS=$2
      shift; shift
      ;;
    --push)
      PUSH=true
      shift
      ;;
    --no-cache)
      NOCACHE=true
      shift
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

[ -z "$DEST_REPO" ] && usage && exit 1
[ -z "$DEST_TAG" ] && usage && exit 1
$NOCACHE && NOCACHE="--no-cache" || NOCACHE=""

$DOCKER build -f ./matlab-dockerfile/Dockerfile \
    --build-arg MATLAB_RELEASE="${MATLAB_VERSION}" \
    --build-arg MATLAB_PRODUCTS="${MATLAB_PRODUCTS}" \
    -t matlab ${NOCACHE} \
    $SCRIPTPATH

$DOCKER build -f Dockerfile.gui \
    --build-arg BASE_IMAGE=matlab \
    -t ${DEST_REPO}:${DEST_TAG} ${NOCACHE} \
    $SCRIPTPATH

$PUSH && $DOCKER push ${DEST_REPO}:${DEST_TAG}
